spring.application.name=todo-management
spring.datasource.url=jdbc:mysql://localhost:3306/todo_management
spring.datasource.username=appuser
spring.datasource.password=mysql@123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.user.name=nikesh
#spring.security.user.password=password
#spring.security.user.roles=ADMIN, USER, MANAGER

app.jwt-secret=cdc81e8ae6ee59ee7f0da4af2e4c48a8718654e8965188b83c878f45c6a9f232
app.jwt-expiration-milliseconds=604800000